---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: red
spec:
  gateways:
    allow: FromList
    gatewayRefs:
      - name: http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /red
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /
            statusCode: 301
      backendRefs:
        - name: red
          port: 8080
