# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

name: Tag Repository Workflow

permissions:
  packages: write
  attestations: write
  id-token: write

on:
  push:
    paths-ignore:
      # - .github/**
      - .gitignore
      - README.md
    branches:
      - master

jobs:
  image:
    name: Build and push Docker image
    uses: gitops-ci-cd/.github/.github/workflows/docker_image.yml@main
