---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: red
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /red(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: red
                port:
                  name: web
